setblock: cobblestone # Какой блок будет устанавливаться после ломание руды

resoures:
  drop: false # Будут ли дропаться ресурсы после ломания блоки
  straight: false # Будет ли перемещены ресурсы сразу в инвентарь после ломания блока
exp: false # Будет ли дропаться опыт после ломания блока

block-place: # mmine.placeblocks - Возможность ставить блоки в шахте
  enable: true
  message: 'В шахте нельзя ставить блоки;title:  &6&lШахта %nl% Здесь нельзя ставить блоки'

block-break: # mmine.breakblocks - Возможность ломать блоки в шахте
  enable: true
  message: 'Вы не можете ломать другие блоки в шахте;title:  &6&lШахта %nl% Здесь нельзя ломать блоки'

gui:
  name: 'Список шахт' # Имя инвенторя
  item:  # Блоки заполняющие инвентарь

npc: # Настройки нпс ( Нуежны плагины Citizens и CommandNPC
  look: true # Будет ли нпс смотреть за игроком
  skin: 'miner' # Скин нпс
  name: '&6&lШахтер' # Отображаемое имя

checks: # mmine.checks - Не проверять игрока
  gamemode:
    enable: true
    modes: [creative,spectator]
    setmode: survival
    message: 'Здесь нельзя находится с креативом;title:  &6&lШахта %nl% Креатив в шахте запрещён.'
  fly:
    enable: true
    message: 'Здесь нельзя находится с флаем;title:  &6&lШахта %nl% Флай в шахте запрещён.'
messages:
  prefix: '&6Шахта &f> '
  commandmanager:
    title_help: 'Список команд:'
    command_not_found: 'Неизвестная команда.'
    error: 'Произошла ошибка при выполнении данной команды.'
    no_permission: 'У вас нет прав.;title:  &6&lШахта %nl% У вас нет прав.'
  create:
    usage: '&c/mine create <название> &f- Создать шахту'
    no_selection: 'Пожалуйста выделите территорию для создание шахты'
    already: 'Данная шахта уже существует, придумайте другое название.'
    complete: 'Шахта сохранена.;title:  &6&lШахта %nl% Шахта сохранена.'
  remove:
    usage: '&c/mine remove <название> &f- Удалить шахту'
    not-found: 'Данной шахты не существует.'
    complete: 'Шахта успешно удалена.;title:  &6&lШахта %nl% Шахта успешно удалена.'
  reset:
    usage: '&c/mine reset &f- Перезагрузить все блоки в шахте'
    complete: 'Блоки перезагружены.;title:  &6&lШахта %nl% Блоки перезагружены.'
  reload:
    usage: '&c/mine reload &f- Перезагрузить конфиг плагина'
    complete: 'Конфиг перезагружен.;title:  &6&lШахта %nl% Конфиг перезагружен.'
  setnpc:
    usage: '&c/mine setnpc &f- Поставить начальника'
    complete: 'Начальник установлен.;title:  &6&lШахта %nl% Начальник установлен.'
  list:
    usage: '&c/mine list &f- Показать список шахт'
    empty: 'Список шахт пуст.'
    title: 'Список шахт:'
    format: '&c%step%&f. &a%name% &f- %stats%'
    stats: '(&e%min%&f) -> (&e%max%&f), &a%world%'
  salary:
    usage: '&c/mine salary &f- Получить зарплату'
    zero: 'Чтобы получить зарплату, вы должны ломать руды.;title:  &6&lШахта %nl% Чтобы получить зарплату, вы должны ломать руды.'
    complete: 'title:  &6&lШахта %nl% Вы получили зарплату в размере &c%salary%$;actionbar:Вы получили зарплату в размере &c%salary%$'
  block:
    complete: 'actionbar:Вы получили &c%salary%$ &fза ломание блока: &c%block%'
ores:
  iron_ore: # Тип блока
    money: 100 # Зарплата за 1 блок
    update: 10 # Обновление блока (в секундах)
    prefix: '&6Железная руда' # Префикс для отображение какой блок вы сломали (при желании можно убрать)
  coal_ore:
    money: 250
    update: 10
    prefix: '&7Угольная руда'
  diamond_ore:
    money: 1000
    update: 10
    prefix: '&bАлмазная руда'
  gold_ore:
    money: 400
    update: 10
    prefix: '&eЗолотая руда'
  emerald_ore:
    money: 2000
    update: 10
    prefix: '&aИзумрудная руда'
  quartz_ore:
    money: 500
    update: 10
    prefix: '&fКварцовая руда'