name: MadMine
author: Hamrusy
version: 2.1
api-version: 1.13
main: ru.hamrusy.madmine.Main
depend: [WorldEdit, Vault, PlaceholderAPI]

commands:
  mine:
    description: Основная команда плагина.
    aliases: [mm, madmine, mmine]